async page => {
 await page.addInitScript(() => localStorage.setItem('candoc-conversation-open','false'));
 const base='http://127.0.0.1:52742', check=(v,m)=>{if(!v)throw Error(m)};
 const get=async p=>(await page.request.get(base+'/api/'+p)).json();
 await page.goto(base);await page.evaluate(()=>{for(const k of Object.keys(localStorage))if(k.startsWith('candoc-review-v1:'))localStorage.removeItem(k)});await page.reload();
 await page.setViewportSize({width:1366,height:768});
 await page.locator('#items .item').first().waitFor();
 const boot=await get('bootstrap'),baseline=await get('document');
 const post=async(p,data)=>(await page.request.post(base+'/api/'+p,{headers:{'X-Candoc-Token':boot.token},data})).json();
 for(const p of await get('proposals'))if(['pending','stale'].includes(p.status))await post('decision',{id:p.id,action:'reject'});
 await page.locator('#search').fill('#/texts/');await page.locator('#search-form button').click();
 await page.locator('[data-queue="#/texts/0"]').waitFor();
 await page.locator('[data-queue="#/texts/0"]').focus();await page.keyboard.press('Enter');
 await page.waitForFunction(()=>window.candocChatContext()?.ref==='#/texts/0');
 await page.locator('#edit-value').fill('UX manual text correction');await page.locator('#reason').fill('A: 시험 Asset에서 직접 작성');
 await page.locator('#chat-toggle').click();await page.locator('#chat-input').fill('A의 미전송 질문');
 await page.locator('[data-queue="#/texts/1"]').click();await page.waitForFunction(()=>window.candocChatContext()?.ref==='#/texts/1');
 check(await page.locator('#reason').inputValue()==='','No reason leakage');check(await page.locator('#chat-input').inputValue()==='','No chat leakage');
 await page.locator('#reason').fill('B의 별도 이유');
 await page.locator('[data-queue="#/texts/0"]').click();await page.waitForFunction(()=>window.candocChatContext()?.ref==='#/texts/0');
 check(await page.locator('#edit-value').inputValue()==='UX manual text correction','A correction restored');
 check(await page.locator('#chat-input').inputValue()==='A의 미전송 질문','A chat draft restored');
 await page.reload();await page.waitForFunction(()=>window.candocChatContext()?.ref==='#/texts/0');
 check(await page.locator('#edit-value').inputValue()==='UX manual text correction','Reload draft exact');
 check(await page.locator('#reason').inputValue()==='A: 시험 Asset에서 직접 작성','Reload reason exact');
 check(await page.locator('#worklist').isVisible(),'Reload worklist exact');
 const historyBefore=(await get('history')).length;
 check((await get('bootstrap')).revision===boot.revision,'Navigation and drafts never approve');
 // Lose the creation response AFTER the server accepted it, then retry the same ID.
 let intercepted=false;
 await page.route('**/api/propose',async route=>{if(!intercepted){intercepted=true;await route.fetch();await route.abort('failed');}else await route.continue();});
 await page.locator('#manual-propose').click();
 await page.waitForFunction(()=>document.querySelector('#draft-status').textContent.includes('응답'));
 const created=(await get('proposals')).filter(p=>p.request.reason==='A: 시험 Asset에서 직접 작성'&&p.status==='pending');check(created.length===1,'Accepted one proposal before response loss');
 await page.locator('#manual-propose').click();await page.locator(`[data-proposal="${created[0].id}"]`).waitFor();
 await page.unroute('**/api/propose');
 check((await get('proposals')).filter(p=>p.request.reason==='A: 시험 Asset에서 직접 작성'&&p.status==='pending').length===1,'Retry created no duplicate');
 check(JSON.stringify(await get('document'))===JSON.stringify(baseline),'Proposal did not change document');
 await page.locator('[data-view]').click();
 check(await page.locator('#proposal-review').isVisible(),'Source view retains proposal');
 await page.locator(`[data-approve="${created[0].id}"]`).focus();
 const scroll=await page.locator('.detail-body').evaluate(el=>el.scrollTop);
 const second=await post('propose',{asset_id:boot.asset.asset_id,revision:boot.revision,ref:'#/texts/1',op:'text',value:'UX independent B',reason:'Later proposal focus regression'});
 await page.waitForFunction(()=>document.querySelector('#proposal-updates').textContent.includes('새 제안'));
 check(await page.locator('#proposal-choice').inputValue()===created[0].id,'New proposal does not replace active ID');
 check(await page.locator('.detail-body').evaluate(el=>el.scrollTop)===scroll,'New proposal preserves scroll');
 check(await page.locator(`[data-approve="${created[0].id}"]`).evaluate(el=>el===document.activeElement),'New proposal preserves focus');
 await page.screenshot({path:'verification/conversation-20261006/after-laptop-text.png'});
 await page.locator(`[data-approve="${created[0].id}"]`).click();
 await page.waitForFunction(()=>document.querySelector('#proposal-content [data-status="applied"]'));
 check((await get('document')).texts[0].text==='UX manual text correction','Exact human text approved');
 check((await get('history')).length===historyBefore+1,'One approval once');
 await page.locator('#work-next').click();await page.waitForFunction(()=>window.candocChatContext()?.ref==='#/texts/1');
 check(await page.locator('#worklist').isVisible(),'Same list after approval and next');
 check(await page.locator('#reason').inputValue()==='B의 별도 이유','B reason remains bound');
 await page.locator('#proposal-hide').click();
 await page.locator('#search').fill('Basso');await page.locator('#search-form button').click();
 const cellHit=page.locator('[data-queue="#/tables/0/cells/0"]');await cellHit.waitFor();
 check((await cellHit.innerText()).includes('Basso'),'Search shows actual matching cell text');
 await cellHit.focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>window.candocChatContext()?.cell===0);
 check(await page.locator('#cell').inputValue()==='0','Keyboard search selects index zero');
 await page.locator('#edit-value').fill('UX manual cell correction');await page.locator('#reason').fill('셀 0의 직접 수정 시험');await page.locator('#manual-propose').click();
 await page.waitForFunction(()=>document.querySelector('#proposal-content .reason')?.textContent.includes('셀 0의 직접'));
 const cellProposal=(await get('proposals')).find(p=>p.request.reason==='셀 0의 직접 수정 시험');
 check((await get('document')).tables[0].data.table_cells[0].text===baseline.tables[0].data.table_cells[0].text,'Cell not applied at creation');
 await page.locator('[data-view]').click();
 check((await page.locator('.diff pre').first().textContent())===baseline.tables[0].data.table_cells[0].text,'Exact cell before content');
 await page.locator('#chat-toggle').click();
 const source=await page.locator('.source').boundingBox(),detail=await page.locator('.detail').boundingBox(),chat=await page.locator('#chat-panel').boundingBox();
 check(chat.x+chat.width<=source.x&&chat.x+chat.width<=detail.x,'Chat does not cover source or review');
 await page.screenshot({path:'verification/conversation-20261006/after-laptop-cell-chat.png'});
 await page.setViewportSize({width:1920,height:1080});await page.screenshot({path:'verification/conversation-20261006/after-desktop-cell-chat.png'});
 await page.locator(`[data-approve="${cellProposal.id}"]`).click();await page.waitForFunction(()=>document.querySelector('#proposal-content [data-status="applied"]'));
 check((await get('document')).tables[0].data.table_cells[0].text==='UX manual cell correction','Exact human cell approved');
 await page.locator('#work-next').click();await page.waitForFunction(()=>window.candocChatContext()?.ref==='#/tables/3');
 check(await page.locator('#worklist').isVisible(),'Cell search list retained after next');
 await page.reload();await page.waitForFunction(()=>window.candocChatContext()?.ref==='#/tables/3');
 check(await page.locator('#worklist').isVisible(),'Search cell work context survives reload');
 // Reverse the two UI approvals through the UI, preserving original source.
 for(let i=0;i<2;i++){await page.locator('#history').click();await page.locator('#undo').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open&&document.querySelector('#message').textContent.includes('되돌렸습니다'));}
 check(JSON.stringify(await get('document'))===JSON.stringify(baseline),'UI undo restores trial baseline');
 // The unused fixture proposal is rejected explicitly in its review panel.
 await page.locator('#proposals').click();await page.locator('#proposal-choice').selectOption(second.id);await page.locator(`[data-reject="${second.id}"]`).click();await page.waitForFunction(()=>document.querySelector('#proposal-content [data-status="rejected"]'));
 return {result:'PASS',manual_without_codex:true,target_drafts:true,keyboard_cell_zero:true,idempotent_creation:true,stable_proposal_focus:true,source_with_proposal:true,continuous_list:true,undo:2};
}
